name: by-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - git
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - requests
      - uv
      - nvidia-nat
      - nemo-gym
      - megatron-bridge
      - git+https://github.com/NVIDIA-NeMo/RL.git
      - git+https://github.com/NVIDIA-NeMo/ProRL-Agent-Server.git
