name: by-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - git
  - jupyterlab
  - ipykernel
  - pip
  - matplotlib
  - pip:
      - requests
      - uv
      - nvidia-nat
      - nemo-gym
      - openpipe-art
